apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: quarkus-petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: quarkus-petclinic
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/vchrisb/quarkus-petclinic
      ref:
        branch: tap
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  serviceClaims:
    - name: postgres-db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: psql-claim-5